const data = {
    products: [
        {
            _id: '1',
            name: 'Brownie Bites',
            category: 'Food',
            image: '/images/p1.jpg',
            price: 50,
            countInStock: 10,
            brand:'SUPER DELIGHT',
            rating: 4.5,
            numReviews: 18,
            description: '200 GRAMS with real Chocolate Chip!'
        },
        {
            _id: '2',
            name: 'Cheese & Choco',
            category: 'Food',
            image: '/images/p2.jpg',
            price: 130,
            countInStock: 10,
            brand: 'BIG ROLLS',
            rating: 5,
            numReviews: 9,
            description: 'BIG Size! BIg Bites!'
        },
        {
            _id: '3',
            name: 'Barquillios',
            category: 'Food',
            image: '/images/p3.jpg',
            price: 50,
            countInStock: 10,
            brand: 'SNACKERS',
            rating: 4,
            numReviews: 5,
            description: 'Delicious Foods and Snacks'
        },
        {
            _id: '4',
            name: 'Chocolate Chip Cookies',
            category: 'Food',
            image: '/images/p4.jpg',
            price: 80,
            countInStock: 10,
            brand: 'SUPER DELIGHT',
            rating: 4.5,
            numReviews: 14,
            description: 'Delicious Foods and Snacks'
        },
        {
            _id: '5',
            name: 'Black&White Cookies',
            category: 'Food',
            image: '/images/p5.jpg',
            price: 95,
            countInStock: 10,
            brand: 'KHONG GUAN',
            rating: 5,
            numReviews: 16,
            description: 'Delicious Foods and Snacks'
        },
        {
            _id: '6',
            name: 'WAFER Choco & Vanilla',
            category: 'Food',
            image: '/images/p6.jpg',
            price: 50,
            countInStock: 0,
            brand: 'WAFER',
            rating: 5,
            numReviews: 11,
            description: 'Delicious Foods and Snacks'
        },
        {
            _id: '7',
            name: 'Pringles',
            category: 'Food',
            image: '/images/p7.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Pringles',
            rating: 5,
            numReviews: 11,
            description: 'Delicious Foods and Snacks'
        },
        {
            _id: '8',
            name: 'Pringles',
            category: 'Food',
            image: '/images/p8.jpg',
            price: 120,
            countInStock: 100,
            brand: 'Pringles',
            rating: 5,
            numReviews: 11,
            description: 'Delicious Foods and Snacks'
        },
        {
            _id: '9',
            name: 'Premium Chocolate Wafer',
            category: 'Food',
            image: '/images/p9.jpg',
            price: 50,
            countInStock: 100,
            brand: 'LEXI',
            rating: 5,
            numReviews: 24,
            description: 'Delicious Foods and Snacks'
        },
        {
            _id: '10',
            name: 'Gery Chocolatos',
            category: 'Food',
            image: '/images/p10.jpg',
            price: 50,
            countInStock: 100,
            brand: 'Garuda Food',
            rating: 5,
            numReviews: 24,
            description: 'Delicious Foods and Snacks'
        },
        {
            _id: '11',
            name: 'Choco Mallows',
            category: 'Food',
            image: '/images/p11.jpg',
            price: 70,
            countInStock: 100,
            brand: 'FIBISCO',
            rating: 4.9,
            numReviews: 24,
            description: 'Delicious Foods and Snacks'
        },
        {
            _id: '12',
            name: 'Choco Crunchies',
            category: 'Food',
            image: '/images/p12.jpg',
            price: 65,
            countInStock: 100,
            brand: 'FIBISCO',
            rating: 4.9,
            numReviews: 24,
            description: 'Delicious Foods and Snacks'
        },
    ],
};
export default data;